version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
volumes:
  influxdb-data:
